# 🎓 Day 1 · Session 3
# 03D · Prompt Engineering Workshop
## Prompt debugging, AI Mythbusters, AI Pulse and faculty prompt toolkit

## 🎯 Learning Objectives

- Debug weak prompts
- Build prompt toolkit
- Discuss model training philosophies

## 🔧 Setup

Expected `.env` file in the same folder as this notebook:

```env
OPENAI_API_KEY=sk-your-key-here
```

In [ ]:
# Uncomment if required
# %pip install openai python-dotenv pandas

In [2]:
import os
from pathlib import Path
from dotenv import load_dotenv, dotenv_values
from openai import OpenAI
import pandas as pd
import json

In [3]:
repo_root = Path.cwd()

while not (repo_root / ".git").exists() and repo_root != repo_root.parent:
    repo_root = repo_root.parent

env_path = repo_root / ".env"

print("Repository root:", repo_root)
print("Loading .env from:", env_path)
print("Env exists:", env_path.exists())

load_dotenv(env_path, override=True)

api_key = os.getenv("OPENAI_API_KEY")

if not api_key:
    raise ValueError(f"OPENAI_API_KEY not found in {env_path}")

client = OpenAI(api_key=api_key)

print("OpenAI client initialized successfully.")

Repository root: /Users/suresh/Projects/teaching/fdp-llm-agentic-ai
Loading .env from: /Users/suresh/Projects/teaching/fdp-llm-agentic-ai/.env
Env exists: True
OpenAI client initialized successfully.

In [4]:
def ask_openai(prompt, model="gpt-4o-mini", temperature=0.3,
               system_prompt="You are a helpful AI teaching assistant.",
               max_tokens=800):
    response = client.chat.completions.create(
        model=model,
        temperature=temperature,
        max_tokens=max_tokens,
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": prompt}
        ]
    )
    return response.choices[0].message.content

# 1️⃣ AI Mythbusters #3

Myth: Prompt engineering is becoming irrelevant because models are getting smarter.

Reality: clear task, context, constraints and output format still matter.

# 2️⃣ Prompt Debugging Checklist

In [5]:
pd.DataFrame([
    {"Question": "Is the task clear?", "Fix": "State exactly what output is needed"},
    {"Question": "Is the audience specified?", "Fix": "Mention student level/background"},
    {"Question": "Is context provided?", "Fix": "Add what the learner already knows"},
    {"Question": "Is output format specified?", "Fix": "Ask for bullets/table/JSON"},
    {"Question": "Are there too many tasks?", "Fix": "Split into smaller prompts"},
    {"Question": "Are examples needed?", "Fix": "Add 2-3 few-shot examples"},
    {"Question": "Are constraints clear?", "Fix": "Set length, tone, style, exclusions"}
])

                      Question                                  Fix
0           Is the task clear?  State exactly what output is needed
1   Is the audience specified?     Mention student level/background
2         Is context provided?   Add what the learner already knows
3  Is output format specified?           Ask for bullets/table/JSON
4    Are there too many tasks?           Split into smaller prompts
5         Are examples needed?            Add 2-3 few-shot examples
6       Are constraints clear?  Set length, tone, style, exclusions

# 3️⃣ Debug a Bad Prompt

In [6]:
bad_prompt = "Make questions on AI"
print(ask_openai(bad_prompt))

Sure! Here are some questions on AI that cover various aspects, including its concepts, applications, ethics, and future implications:

### General Questions
1. What is artificial intelligence, and how is it different from traditional programming?
2. What are the main types of AI, and can you provide examples of each?
3. How do machine learning and deep learning differ from one another?
4. What role does data play in training AI models?
5. Can you explain the concept of neural networks and how they function?

### Applications of AI
6. In what industries is AI currently being used, and what are some specific applications within those industries?
7. How is AI transforming healthcare, and what are some potential benefits and challenges?
8. What are some examples of AI in everyday consumer products?
9. How is AI being utilized in autonomous vehicles?
10. What is natural language processing (NLP), and how is it applied in AI systems?

### Ethical Considerations
11. What are some ethical concerns associated with the use of AI?
12. How can bias in AI algorithms affect decision-making processes?
13. What measures can be taken to ensure transparency and accountability in AI systems?
14. How does AI impact job displacement, and what are potential solutions to this issue?
15. What are the implications of AI in surveillance and privacy?

### Future of AI
16. What advancements in AI do you foresee in the next decade?
17. How might AI influence the future of education and learning?
18. What are the potential risks of developing superintelligent AI?
19. How can society prepare for the widespread adoption of AI technologies?
20. What role do you think AI will play in addressing global challenges such as climate change and poverty?

Feel free to use or modify these questions as needed!

In [7]:
debugged_prompt = """
You are an examiner for a 3rd-year B.Tech AI course.

Create 5 MCQ questions on Introduction to Artificial Intelligence.

Requirements:
- Difficulty: Medium
- Each question must have 4 options
- Include correct answer
- Include one-line explanation
- Avoid ambiguous options
- Cover different subtopics: search, ML, neural networks, ethics, agents

Return as a numbered list.
"""
print(ask_openai(debugged_prompt, max_tokens=1200))

Here are five multiple-choice questions on the Introduction to Artificial Intelligence:

1. **Which of the following search algorithms guarantees finding the optimal solution if one exists?**
   A) Depth-First Search
   B) Breadth-First Search
   C) A* Search
   D) Greedy Best-First Search
   **Correct Answer:** C) A* Search
   *Explanation: A* Search uses heuristics to find the optimal path while considering both cost and estimated distance to the goal.*

2. **In machine learning, which of the following is a common method for supervised learning?**
   A) K-means Clustering
   B) Decision Trees
   C) Principal Component Analysis
   D) Reinforcement Learning
   **Correct Answer:** B) Decision Trees
   *Explanation: Decision Trees are a popular supervised learning method used for classification and regression tasks.*

3. **What is the primary function of activation functions in neural networks?**
   A) To initialize weights
   B) To combine inputs
   C) To introduce non-linearity
   D) To normalize data
   **Correct Answer:** C) To introduce non-linearity
   *Explanation: Activation functions allow neural networks to learn complex patterns by introducing non-linear transformations of the input data.*

4. **Which ethical concern is commonly associated with the deployment of AI systems?**
   A) Increased computational power
   B) Data privacy and security
   C) Improved algorithm efficiency
   D) Enhanced user experience
   **Correct Answer:** B) Data privacy and security
   *Explanation: The use of AI often involves processing large amounts of personal data, raising concerns about privacy and security.*

5. **In the context of AI agents, what does the term "environment" refer to?**
   A) The hardware on which the agent runs
   B) The set of rules governing the agent's behavior
   C) The external context in which the agent operates
   D) The programming language used to develop the agent
   **Correct Answer:** C) The external context in which the agent operates
   *Explanation: The environment encompasses everything the agent interacts with, including other agents and the conditions affecting its actions.*

# 4️⃣ Prompt Clinic

In [8]:
pd.DataFrame({"Weak Prompt": [
    "Explain DBMS",
    "Give notes on neural networks",
    "Make assignment questions",
    "Check this answer",
    "Summarize this paper"
]})

                     Weak Prompt
0                   Explain DBMS
1  Give notes on neural networks
2      Make assignment questions
3              Check this answer
4           Summarize this paper

# 5️⃣ Faculty Toolkit Builder

In [9]:
subject = "Machine Learning"
student_level = "2nd-year engineering students"

toolkit_prompt = f"""
Create a reusable prompt toolkit for a faculty member teaching {subject} to {student_level}.

Include 8 prompt templates:
1. Concept explainer
2. Analogy generator
3. MCQ generator
4. Assignment feedback
5. Viva question generator
6. Lab activity generator
7. Common misconception finder
8. Research summary assistant

For each template include:
- Template name
- Full reusable prompt
- When to use it
"""
print(ask_openai(toolkit_prompt, max_tokens=1800))

### Reusable Prompt Toolkit for Teaching Machine Learning

---

#### 1. Concept Explainer
- **Template Name:** Concept Explainer
- **Full Reusable Prompt:** "Explain the concept of [insert concept] in machine learning in simple terms. Include key points, examples, and its significance in the field."
- **When to Use It:** Use this prompt when introducing new concepts to students or when they request clarification on specific topics.

---

#### 2. Analogy Generator
- **Template Name:** Analogy Generator
- **Full Reusable Prompt:** "Create an analogy that explains [insert machine learning concept] in a way that is relatable to everyday experiences. Make it engaging and easy to understand."
- **When to Use It:** Use this prompt when students struggle to grasp complex concepts or when you want to make the material more relatable.

---

#### 3. MCQ Generator
- **Template Name:** MCQ Generator
- **Full Reusable Prompt:** "Generate 5 multiple-choice questions (MCQs) related to [insert topic or concept] in machine learning. Provide the correct answer and a brief explanation for each."
- **When to Use It:** Use this prompt to create quizzes or assessments to evaluate students' understanding of specific topics.

---

#### 4. Assignment Feedback
- **Template Name:** Assignment Feedback
- **Full Reusable Prompt:** "Provide constructive feedback on the following assignment submission: [insert student’s assignment text]. Highlight strengths, areas for improvement, and suggestions for further study."
- **When to Use It:** Use this prompt when reviewing student assignments to provide personalized feedback that encourages learning and improvement.

---

#### 5. Viva Question Generator
- **Template Name:** Viva Question Generator
- **Full Reusable Prompt:** "Generate a list of 10 potential viva questions for a student presenting on [insert topic or project] in machine learning. Include questions that assess both theoretical understanding and practical application."
- **When to Use It:** Use this prompt to prepare students for oral examinations or presentations, ensuring they are ready to defend their work.

---

#### 6. Lab Activity Generator
- **Template Name:** Lab Activity Generator
- **Full Reusable Prompt:** "Design a lab activity focused on [insert machine learning topic or technique]. Include objectives, materials needed, step-by-step instructions, and expected outcomes."
- **When to Use It:** Use this prompt to create hands-on lab sessions that reinforce theoretical concepts through practical application.

---

#### 7. Common Misconception Finder
- **Template Name:** Common Misconception Finder
- **Full Reusable Prompt:** "Identify common misconceptions students might have about [insert machine learning concept]. Explain why these misconceptions are incorrect and provide correct information."
- **When to Use It:** Use this prompt to proactively address misunderstandings that may hinder students' learning and to clarify complex topics.

---

#### 8. Research Summary Assistant
- **Template Name:** Research Summary Assistant
- **Full Reusable Prompt:** "Summarize the key findings and implications of the following research paper: [insert paper title and authors]. Focus on how it contributes to the field of machine learning."
- **When to Use It:** Use this prompt to help students understand and synthesize research literature, especially when preparing for projects or presentations.

---

This toolkit provides a structured approach to enhance the teaching and learning experience in machine learning for 2nd-year engineering students. Each template can be adapted to specific topics and needs as they arise throughout the course.

# 6️⃣ AI Pulse: How Labs Train Differently

OpenAI: RLHF. Anthropic: Constitutional AI. Google: multimodal and efficiency. DeepSeek: RLVR/verifiable rewards.

Question: If you were building an LLM for education, what would you optimize for?

# 7️⃣ Prompt Engineering Ladder

In [10]:
pd.DataFrame([
    {"Level": 1, "Skill": "Ask directly", "Example": "Explain overfitting"},
    {"Level": 2, "Skill": "Add audience", "Example": "Explain to 2nd-year students"},
    {"Level": 3, "Skill": "Add persona", "Example": "You are a patient tutor"},
    {"Level": 4, "Skill": "Add context", "Example": "They know train/test split"},
    {"Level": 5, "Skill": "Add format", "Example": "Use a table"},
    {"Level": 6, "Skill": "Add constraints", "Example": "Avoid equations"},
    {"Level": 7, "Skill": "Add examples", "Example": "Here are two sample outputs"},
    {"Level": 8, "Skill": "Prompt chain", "Example": "Explain -> quiz -> activity"}
])

   Level            Skill                       Example
0      1     Ask directly           Explain overfitting
1      2     Add audience  Explain to 2nd-year students
2      3      Add persona       You are a patient tutor
3      4      Add context    They know train/test split
4      5       Add format                   Use a table
5      6  Add constraints               Avoid equations
6      7     Add examples   Here are two sample outputs
7      8     Prompt chain   Explain -> quiz -> activity

# 8️⃣ Capstone Challenge

Build 5 reusable prompts for your subject: Explainer, Examiner, Grader, Socratic Tutor and Research Assistant.

In [ ]:
capstone_template = """
Prompt Name:
Purpose:
Subject:
Target Student Level:

Reusable Prompt:
---
[Write the full prompt here]
---

Example Input:
Expected Output Format:
"""
print(capstone_template)

# ✅ Summary

Good prompt engineering is clear communication with the model. The output improves when the task, audience, context, format and constraints are clear.